### ISSUE TITLE
TaskGroup not introduced until python 3.11

### ISSUE THREAD

**Issue by ircwaves** [gadomski/stac-asset#10]
`pyproject.toml` should probably reflect usage of the `TaskGroup` feature, [introduced in 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#asyncio) here:

https://github.com/gadomski/stac-asset/blob/b472a56faba5d2f2a4647c860f2eb6f978c9aa24/pyproject.toml#L15

or things could get reworked to a 3.8 compatible implementation.

**Comment by gadomski** [comment]
Where's `TaskGroup` used?

**Comment by gadomski** [comment]
@ircwaves you did prompt me to add multi-python testing: https://github.com/gadomski/stac-asset/pull/12

**Comment by gadomski** [comment]
@ircwaves try me meow: https://pypi.org/project/stac-asset/0.0.3/

**Comment by ircwaves** [comment]
That did the trick. `stac_asset.client` in `v0.0.2`.  Fixed in `v0.0.3`.
